### ISSUE TITLE
Refine Edges Control PREVIEW

### ISSUE THREAD

**Issue by AlonDan** [Zarxrax/Cutie-Roto#3]
I noticed that the **gui_config.yaml** have also control of the Refine Edges.
If you'll be able to allow to change it and SEE how it will look on **PREVIEW** (before rendering) that will be very useful!

Also, is there a way to make the Background Color BLACK by default? currently it's green
I didn't see it on the config but I may missed it.

**Comment by Zarxrax** [comment]
It will be very difficult to add the refine edges into the preview (because it is not generated until exporting, and requires to have already propagated across all frames). So for now, I do not anticipate adding such a feature. I recommend adjusting the edge size within an editing application.

I don't currently have an option in the config to set the background color. But as a workaround, you can set the background image to a solid black image.

**Comment by AlonDan** [comment]
I did some extreme tests with the REFINE EDGES and no matter if I use for example erode 3 or 99 same for the Blur, even if I go extremes, when render I see no difference at all.

Can you test and see if it's working at all or the GUI config won't really apply the changes?

**Comment by Zarxrax** [comment]
Yes, it works, but I think maybe it doesn't do what you are thinking it does. It doesn't grow or shrink the mask size, but merely combines together 2 kinds of masks that cutie generates.

The primary mask reflects what is shown on the preview. Pixels are either turned on or off. It has a very blocky, pixelated look, but it perfectly reflects what you see in the preview, according to the click selections that you made.

Next is the soft mask. This gets generated by the neural network when you run propagation. It calculates the mask for each frame based on the previous frames and reference frames. This mask is "soft" because it is all shades of gray. It might include some extra areas that you didn't click on, and it might not include some areas that its supposed to. However, the soft mask has really nice edges.

The refined mask is an attempt to merge the 2 masks together to get the accuracy of the primary mask with the soft edges from the soft mask. You can see the comparisons below, and also by looking at the folders within your workspace.

![0000072mask](https://github.com/Zarxrax/Cutie-Roto/assets/16127268/079d9fe5-53cd-4b65-8652-a5ea1696ba16)
![0000072soft](https://github.com/Zarxrax/Cutie-Roto/assets/16127268/6c3e584d-1043-4ada-9ee2-808d7a240438)
![0000072refined](https://github.com/Zarxrax/Cutie-Roto/assets/16127268/2ef3f4e8-9321-4581-98d7-690d0d534b82)

**Comment by AlonDan** [comment]
Thanks for the reply, I thought the refine and the erode will work like any other composite / editing video but I guess it doesn't so I still have to make that on another app.
